apiVersion: v1
kind: Service
metadata:
  name: ifra-docs-service
  labels:
    app: ifra-docs
spec:
  type: NodePort
  ports:
    - port: 80
      name: http
  selector:
    app: ifra-docs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ifra-docs
spec:
  selector:
    matchLabels:
      app: ifra-docs
  replicas: 1
  template:
    metadata:
      labels:
        app: ifra-docs
    spec:
      containers:
      - name: ifra-docs
        image: ifrasoft/ifra-docs:{{IFRA_CMS_TAG}}